const TYPES = {
  SET_IS_LOADING: 'SET_IS_LOADING',
  SET_SOCIALS: 'SET_SOCIALS',
  SET_SOCIAL: 'SET_SOCIAL',
  SET_SELECTED_SOCIAL_INDEX: 'SET_SELECTED_SOCIAL_INDEX',
  ADD_SOCIAL: 'ADD_SOCIAL',
  REMOVE_SOCIAL: 'REMOVE_SOCIAL',
  UPDATE_SOCIAL: 'UPDATE_SOCIAL',
  SET_FE_DISPLAY_SETTINGS: 'SET_FE_DISPLAY_SETTINGS',
};
export default TYPES;