server {
  listen 443 ssl;
  server_name adminer.jin-dev.test;

  ssl_certificate     /etc/nginx/certs/self-signed/jin-dev.test.pem;
  ssl_certificate_key /etc/nginx/certs/self-signed/jin-dev.test-key.pem;

  location / {
    proxy_pass http://adminer:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}