upstream php {
  server php:9000;
}

server {
  listen 80;
  server_name jin-dev.test;

  root /var/www/html;
  index index.php index.html;

  location / {
    try_files $uri $uri/ /index.php?$args;
  }

  location ~ \.php$ {
    include        fastcgi_params;
    fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_intercept_errors on;
    fastcgi_pass   php;
  }
}

server {
  listen 443 ssl;
  server_name jin-dev.test;

  ssl_certificate     /etc/nginx/certs/self-signed/jin-dev.test.pem;
  ssl_certificate_key /etc/nginx/certs/self-signed/jin-dev.test-key.pem;

  root /var/www/html;
  index index.php index.html;

  location / {
    try_files $uri $uri/ /index.php?$args;
  }

  location ~ \.php$ {
    include        fastcgi_params;
    fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_intercept_errors on;
    fastcgi_pass   php;
  }
}